### DISCUSSION TITLE
What is the supposed behavior when NAMESUBLANG is empty?

### DISCUSSION THREAD

**Discussion by janusn** [McCloudS/subgen#164] [Q&A] [answered]
With the following docker compose.yaml file:
```
---
services:
  subgen:
    image: mccloud/subgen:cpu
    container_name: subgen-monitor-eng
    deploy:
      resources:
        limits:
          memory: 16G
    restart: unless-stopped
    ports:
      - "9010:9000"
    volumes:
      - ./models:/models:rw
      - "/mnt/media:/mnt/media:rw"
      - "/mnt/private:/mnt/private:rw"
    environment:
      - TRANSCRIBE_DEVICE=cpu
      - WHISPER_MODEL=base
      - CONCURRENT_TRANSCRIPTIONS=2
      - WHISPER_THREADS=12
      - MODEL_PATH=/models
      - NAMESUBLANG=eng

      - APPEND=True
      - DETECT_LANGUAGE_OFFSET=180
      - DETECT_LANGUAGE_LENGTH=30
      - MONITOR=True
      - SHOULD_WHISPER_DETECT_AUDIO_LANGUAGE=True
      - SKIP_IF_TO_TRANSCRIBE_SUB_ALREADY_EXIST=True
      - SKIPIFEXTERNALSUB=True
      - SUBTITLE_LANGUAGE_NAMING_TYPE=ISO_639_2_T
      - TRANSCRIBE_FOLDERS="/mnt/media/Movies"
      - TRANSCRIBE_OR_TRANSLATE=translate
```

It named a subtitle file as `[video name].subgen.base.rus.srt` when it translated a video with Russian audio. I thought it would name it as `[video name].subgen.base.eng.srt` instead.
