### ISSUE TITLE
[request] Less bigger image

### ISSUE THREAD

**Issue by Tuumke** [McCloudS/subgen#57]
Would be sweet to have the option / tag / branch to have a smaller image again.

People use docker-compose to pull in their stack. Each time i do and subgen has a new docker image, i gotta pull in 6gb. This makes me want to update my docker containers less. It's not how docker is supposed to work. Docker is meant for the smallest possible images. So would be nice to have something without the CUDA images and associated packages for those running CPU only.

If you need any help with this, i've got some experience as well

**Comment by McCloudS** [comment]
The bigger issue is GitHub actions doesn’t use cached images and so it rebuilds 100% of the time, negating the cachiness of docker.

I can look at adding it back if I can simplify it.  It was originally removed so I didn’t have to ‘maintain’ more than 1 image.  I can probably simplify it by moving a requirements.txt into the repo and adding that.

**Comment by Tuumke** [comment]
Could also have a seperate branche for it? That's how i maintained a dev and production container. Not sure if that would work in this case. Or maybe change the workflow to make another build with seperate Dockerfile

```
steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./api/Service/ --file Dockerfile --tag my-image-name:$(date +%s)
```
Not sure if that works but got it from [here](https://stackoverflow.com/questions/61874021/how-do-i-specify-the-dockerfile-location-in-my-github-action)
